version: "3.8"
services:
  script:
    build: .
    networks:
      xrnl-bridge:
        ipv4_address: 172.22.0.100
    volumes:
      - logs:/var/log/fb-events-syncer
volumes:
  logs:
networks:
  default:
    external:
      name: xrnl-bridge
  xrnl-bridge:
    external: true
